public with sharing class VR_Constants {

    public static final String SUCCESS = 'success';
    public static final String MESSAGE = 'message';

    //Rest
    public static final String HEADER_AUTHORIZATION = 'Authorization';
    public static final String HEADER_ORG_ID = 'OpenAI-Organization';
    public static final String HEADER_ACCEPT = 'Accept';
    public static final String HEADER_CONTENT_TYPE = 'Content-Type';
    public static final String HEADER_APPLICATION_JSON = 'application/json';
    public static final String METHOD_POST = 'POST';
    public static final String METHOD_GET = 'GET';

    public static final String IMAGE_RESPONSE = 'imageResponse';

}